import * as THREE from "three";
import { OrbitControls } from "three/examples/jsm/controls/OrbitControls.js";
import * as dat from "lil-gui";
import { genererFigures } from "./figures";
import {CSG} from "three-csg-ts";

/**
 * Base
 */
// Debug
const gui = new dat.GUI();

// Canvas
const canvas = document.querySelector("canvas.webgl");

// Scene
const scene = new THREE.Scene();

/**
 * Lights
 */
// Ambient light
const ambientLight = new THREE.AmbientLight(0xffffff, 0.5);
gui.add(ambientLight, "intensity").min(0).max(1).step(0.001);
scene.add(ambientLight);

// Directional light
const directionalLight = new THREE.DirectionalLight(0xffffff, 0.6);
directionalLight.position.set(2, 2, -1);
gui.add(directionalLight, "intensity").min(0).max(1).step(0.001);
gui.add(directionalLight.position, "x").min(-5).max(5).step(0.001);
gui.add(directionalLight.position, "y").min(-5).max(5).step(0.001);
gui.add(directionalLight.position, "z").min(-5).max(5).step(0.001);
scene.add(directionalLight);
directionalLight.castShadow = true;

directionalLight.shadow.mapSize.width = 2048;
directionalLight.shadow.mapSize.height = 2048;
directionalLight.shadow.camera.top = 2;
directionalLight.shadow.camera.bottom = -2;
directionalLight.shadow.camera.right = 2;
directionalLight.shadow.camera.left = -2;
directionalLight.shadow.camera.near = 1;
directionalLight.shadow.camera.far = 8;
// directionalLight.shadow.radius = 10

const directionalLightCameraHelper = new THREE.CameraHelper(
  directionalLight.shadow.camera
);
directionalLightCameraHelper.visible = false;
scene.add(directionalLightCameraHelper);

/**
 * Materials
 */
const material = new THREE.MeshStandardMaterial();
material.roughness = 0.7;
gui.add(material, "metalness").min(0).max(1).step(0.001);
gui.add(material, "roughness").min(0).max(1).step(0.001);

/**
 * Objects
 *
 * Object meshes are generated by the anaverse-compatible
 * figures.js script. This script yields a "figures" array
 * containing the information necessary to build & position
 * a THREE mesh.
 *
*/

const figures = genererFigures(fxhash).figures;

var figureMap = {};

// mapping them by name makes the easier to use
figures.forEach((fig) => (figureMap[fig.name] = fig));

// Add objects using the figure map.
// Here they are added one by one
// but one could simply iterate over the figures array
// to add them all at once.

// const box = new THREE.Mesh(
//   new THREE[figureMap.box.geometry.type](...figureMap.box.geometry.args),
//   material
// );
// box.position.set(figureMap.box.pos.x, figureMap.box.pos.y, figureMap.box.pos.z);
// box.castShadow = true;
// box.receiveShadow = true;

const plane = new THREE.Mesh(
  new THREE[figureMap.plane.geometry.type](...figureMap.plane.geometry.args),
  material
);
plane.rotation.x = figureMap.plane.rot.x;
plane.position.y = figureMap.plane.pos.y;

plane.receiveShadow = true;

scene.add(plane);

/**
 * Constructive Solid Geometry Tests
*/
// let meshA = new THREE.Mesh(new THREE.BoxGeometry(1,1,1), material);
// let meshB = new THREE.Mesh(new THREE.BoxGeometry(1,1,1), material);

const meshA = new THREE.Mesh(
  new THREE[figureMap.box.geometry.type](...figureMap.box.geometry.args),
  material
);
const meshB = new THREE.Mesh(
  new THREE[figureMap.box.geometry.type](...figureMap.box.geometry.args),
  material
);

meshB.position.add(new THREE.Vector3( 0.5, 0.5, 0.5));

meshA.updateMatrix();
meshB.updateMatrix();

let bspA = CSG.fromMesh( meshA );
let bspB = CSG.fromMesh( meshB );

let bspResult = bspA.union(bspB);
let meshResult = CSG.toMesh( bspResult, meshA.matrix, meshA.material );

scene.add(meshResult); // <---- anaglyphic does this work for anaver.se integration?

/**
 * Sizes
 */
const sizes = {
  width: window.innerWidth,
  height: window.innerHeight,
};

window.addEventListener("resize", () => {
  // Update sizes
  sizes.width = window.innerWidth;
  sizes.height = window.innerHeight;

  // Update camera
  camera.aspect = sizes.width / sizes.height;
  camera.updateProjectionMatrix();

  // Update renderer
  renderer.setSize(sizes.width, sizes.height);
  renderer.setPixelRatio(Math.min(window.devicePixelRatio, 2));
});

/**
 * Camera
 */
// Base camera
const camera = new THREE.PerspectiveCamera(
  75,
  sizes.width / sizes.height,
  0.1,
  100
);
camera.position.x = 1;
camera.position.y = 1;
camera.position.z = 2;
scene.add(camera);

// Controls
const controls = new OrbitControls(camera, canvas);
controls.enableDamping = true;

/**
 * Renderer
 */
const renderer = new THREE.WebGLRenderer({
  canvas: canvas,
});
renderer.setSize(sizes.width, sizes.height);
renderer.setPixelRatio(Math.min(window.devicePixelRatio, 2));
renderer.shadowMap.enabled = true; // enable for shadows ;)
renderer.shadowMap.type = THREE.PCFSoftShadowMap;

/**
 * Animate
 *
 * Note here that anaverse doesn't support room animation.
 *
 */
const clock = new THREE.Clock();

const tick = () => {
  const elapsedTime = clock.getElapsedTime();

  // // animate the sphere
  // sphere.position.x = Math.cos(elapsedTime);
  // sphere.position.z = 1 + Math.sin(elapsedTime);
  // sphere.position.y = Math.abs(Math.sin(elapsedTime * 3));

  // Update controls
  controls.update();

  // Render
  renderer.render(scene, camera);

  // Call tick again on the next frame
  window.requestAnimationFrame(tick);
};

tick();